### ISSUE TITLE
[Feature] Dark theme support

### ISSUE THREAD

**Issue by bbb651** [bbodi/notecalc3#7]
This is a pretty basic and simple to add feature that would make the application way more usable for a lot of people.
Should be pretty easy to add using a `@media` tag with `prefers-color-scheme: dark`, or even using css variables and a way to import themes from some format by adding a `style` attribute to set the variables.

**Comment by bbodi** [comment]
Dark theme support is on my list. 
It is simple yes, but not in the way you think. Everything is renderend onto a canvas, so html styling does help much. But yeah still very simple, I have to just replace the rendering colors.
Since you brought it up, I will put it into the next release (0.3.0), will be out probably beginning of January.

**Comment by bbodi** [comment]
![D10nAPmBHz](https://user-images.githubusercontent.com/2362136/101654753-2734f780-3a41-11eb-9291-92062b6457e8.gif)
In progress :)

**Comment by bbb651** [comment]
Oh that's cool! I didn't realize it was a canvas element, I thought it was built using html tags and text.
I'll try cloning it and messing around with it, this looks like a really useful tool.
